# Jekyll config for Handbook site
title: Handbook
description: Quick tech ticks and comparisons
# For a project site under https://rilov.github.io/handbook, set the URL and baseurl below
url: "https://rilov.github.io"
baseurl: "/handbook"

# Collections
collections:
  topics:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown

# Include assets
include:
  - _topics
  - assets
